---

# tasks file for Java Installation

- name: 'check presence of java'
  shell: which java
  register: oracle_java_task_installed
  changed_when: oracle_java_task_installed.rc != 0
  failed_when: no

# oracle_java_installed.rc == 0 : installed
# oracle_java_installed.rc == 1 : not installed

- name: set fact oracle_java_installed
  set_fact:
    oracle_java_installed={{ not oracle_java_task_installed.changed }}

- name: determine which Java version is installed
  shell: java -version
  when: oracle_java_installed
  register: oracle_java_task_version
  changed_when: False

- name: set fact oracle_java_installed_version
  set_fact:
    oracle_java_version_installed="{{ oracle_java_task_version.stderr.split('\n')[0]|regex_replace('.*\"(.*)\"','\\1') }}"
  when: oracle_java_task_version is defined and oracle_java_task_version.stdout is defined
  changed_when: False

- name: Install Java 1.8
  yum: name=java-1.8.0-openjdk state=present
