---


- include_vars: vars.yml

- name: Upload the Artifacts to Jfrog repo
  shell: /usr/local/go/bin/jfrog rt u --url http://{{ ipaddress }}:{{ jfrogport }}/artifactory/sampleweb_mvnrepo/ --user {{ username }} --password {{ password }} {{destlocation }}/simple-web-app.war {{ env }}/{{ buildnumber }}/simple-web-{{ env }}.war
  become: yes
  become_user: root
  when: common == "upload"
- name: Download the Artifacts from Jfrog repo
  shell: /usr/local/go/bin/jfrog rt dl --url http://{{ ipaddress }}:{{ jfrogport }}/artifactory/ --user {{ username }} --password {{ password }} sampleweb_mvnrepo/{{ env }}/{{ buildnumber }}/simple-web-{{ env }}.war {{ downloadpath }}
  when: common == "download"

- name: Upload the Artifacts to Nexus repo
  shell: curl -v -u {{ username }}:{{ password }} --upload-file {{destlocation }}/simple-web-app.war http://{{ ipaddress }}:{{ nexusport }}/nexus/content/repositories/sampleweb_mvnrepo/{{ env }}/{{ buildnumber }}/simple-web-{{ env }}.war
  when: common == "upload"

- name: Download the Artifacts from Nexus repo
  shell: curl -u{{ username }}:{{ password }} -O http://23.251.156.10:8081/nexus/content/repositories/sampleweb_mvnrepo/{{ env }}/{{ buildnumber }}/simple-web-{{ env }}.war
  when: common == "download"
