---


- include_vars: vars.yml

- name: Upload the Artifacts to Jfrog repo
  shell: /usr/local/go/bin/jfrog rt u --url http://{{ ipaddress }}:{{ port }}/artifactory/sampleweb_mvnrepo/ --user {{ username }} --password {{ password }} {{destlocation }}/simple-web-app.war {{ env }}/{{ buildnumber }}/simple-web-{{ env }}.war
  become: yes
  become_user: root
  when: common == "upload"
- name: Download the Artifacts from Jfrog repo
  shell: /usr/local/go/bin/jfrog rt dl --url http://{{ ipaddress }}:{{ port }}/artifactory/ --user {{ username }} --password {{ password }} sampleweb_mvnrepo/{{ env }}/{{ buildnumber }}/simple-web-{{ env }}.war {{ downloadpath }}
  when: common == "download"
