---


- include_vars: vars.yml

- name: hostname details
  shell: curl -u "{{ username }}":"{{password}}" -X PUT "http://{{ ipaddress }}:{{ port }}/artifactory/sampleweb_mvnrepo/{{env}}/{{buildnumber}}/simpleweb-{{env}}.war" -T /home/kishore_donekal/CTCO-Assignment/simple-web-app/target/simple-web-app.war
  tags: upload

- name: hostname details
  command: chdir=/home/kishore_donekal/weblocation curl -u "{{ username }}":"{{password}}" -O "http://{{ ipaddress }}:{{ port }}/artifactory/sampleweb_mvnrepo/{{env}}/{{buildnumber}}/simpleweb-{{env}}.war"
  tags: download
